//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: RouteXModel.kt:8</p>
  /// </summary>
  public class RouteXModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<Unit, List<RdApiEndpoint>> GetEndpoints => _GetEndpoints;
    [NotNull] public IRdEndpoint<Unit, Unit> ClearCache => _ClearCache;
    [NotNull] public ISignal<List<RdApiEndpoint>> EndpointsUpdated => _EndpointsUpdated;
    [NotNull] public ISignal<string> NavigateToEndpoint => _NavigateToEndpoint;
    
    //private fields
    [NotNull] private readonly RdCall<Unit, List<RdApiEndpoint>> _GetEndpoints;
    [NotNull] private readonly RdCall<Unit, Unit> _ClearCache;
    [NotNull] private readonly RdSignal<List<RdApiEndpoint>> _EndpointsUpdated;
    [NotNull] private readonly RdSignal<string> _NavigateToEndpoint;
    
    //primary constructor
    private RouteXModel(
      [NotNull] RdCall<Unit, List<RdApiEndpoint>> getEndpoints,
      [NotNull] RdCall<Unit, Unit> clearCache,
      [NotNull] RdSignal<List<RdApiEndpoint>> endpointsUpdated,
      [NotNull] RdSignal<string> navigateToEndpoint
    )
    {
      if (getEndpoints == null) throw new ArgumentNullException("getEndpoints");
      if (clearCache == null) throw new ArgumentNullException("clearCache");
      if (endpointsUpdated == null) throw new ArgumentNullException("endpointsUpdated");
      if (navigateToEndpoint == null) throw new ArgumentNullException("navigateToEndpoint");
      
      _GetEndpoints = getEndpoints;
      _ClearCache = clearCache;
      _EndpointsUpdated = endpointsUpdated;
      _NavigateToEndpoint = navigateToEndpoint;
      _GetEndpoints.Async = true;
      _ClearCache.Async = true;
      BindableChildren.Add(new KeyValuePair<string, object>("getEndpoints", _GetEndpoints));
      BindableChildren.Add(new KeyValuePair<string, object>("clearCache", _ClearCache));
      BindableChildren.Add(new KeyValuePair<string, object>("endpointsUpdated", _EndpointsUpdated));
      BindableChildren.Add(new KeyValuePair<string, object>("navigateToEndpoint", _NavigateToEndpoint));
    }
    //secondary constructor
    internal RouteXModel (
    ) : this (
      new RdCall<Unit, List<RdApiEndpoint>>(JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid, ReadRdApiEndpointList, WriteRdApiEndpointList),
      new RdCall<Unit, Unit>(JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid, JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid),
      new RdSignal<List<RdApiEndpoint>>(ReadRdApiEndpointList, WriteRdApiEndpointList),
      new RdSignal<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString)
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<List<RdApiEndpoint>> ReadRdApiEndpointList = RdApiEndpoint.Read.List();
    
    public static  CtxWriteDelegate<List<RdApiEndpoint>> WriteRdApiEndpointList = RdApiEndpoint.Write.List();
    
    protected override long SerializationHash => -3893942425860350789L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("RouteXModel (");
      using (printer.IndentCookie()) {
        printer.Print("getEndpoints = "); _GetEndpoints.PrintEx(printer); printer.Println();
        printer.Print("clearCache = "); _ClearCache.PrintEx(printer); printer.Println();
        printer.Print("endpointsUpdated = "); _EndpointsUpdated.PrintEx(printer); printer.Println();
        printer.Print("navigateToEndpoint = "); _NavigateToEndpoint.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionRouteXModelEx
   {
    public static RouteXModel GetRouteXModel(this Solution solution)
    {
      return solution.GetOrCreateExtension("routeXModel", () => new RouteXModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: RouteXModel.kt:50</p>
  /// </summary>
  public sealed class RdApiEndpoint : IPrintable, IEquatable<RdApiEndpoint>
  {
    //fields
    //public fields
    [NotNull] public string Id {get; private set;}
    public RdHttpMethod HttpMethod {get; private set;}
    [NotNull] public string Route {get; private set;}
    [NotNull] public string FilePath {get; private set;}
    public int LineNumber {get; private set;}
    [CanBeNull] public string ControllerName {get; private set;}
    [NotNull] public string MethodName {get; private set;}
    [NotNull] public List<RdApiParameter> Parameters {get; private set;}
    [CanBeNull] public RdApiSchema BodySchema {get; private set;}
    public bool AuthRequired {get; private set;}
    [CanBeNull] public string AuthPolicy {get; private set;}
    [NotNull] public string ContentHash {get; private set;}
    public float AnalysisConfidence {get; private set;}
    [NotNull] public List<string> AnalysisWarnings {get; private set;}
    
    //private fields
    //primary constructor
    public RdApiEndpoint(
      [NotNull] string id,
      RdHttpMethod httpMethod,
      [NotNull] string route,
      [NotNull] string filePath,
      int lineNumber,
      [CanBeNull] string controllerName,
      [NotNull] string methodName,
      [NotNull] List<RdApiParameter> parameters,
      [CanBeNull] RdApiSchema bodySchema,
      bool authRequired,
      [CanBeNull] string authPolicy,
      [NotNull] string contentHash,
      float analysisConfidence,
      [NotNull] List<string> analysisWarnings
    )
    {
      if (id == null) throw new ArgumentNullException("id");
      if (route == null) throw new ArgumentNullException("route");
      if (filePath == null) throw new ArgumentNullException("filePath");
      if (methodName == null) throw new ArgumentNullException("methodName");
      if (parameters == null) throw new ArgumentNullException("parameters");
      if (contentHash == null) throw new ArgumentNullException("contentHash");
      if (analysisWarnings == null) throw new ArgumentNullException("analysisWarnings");
      
      Id = id;
      HttpMethod = httpMethod;
      Route = route;
      FilePath = filePath;
      LineNumber = lineNumber;
      ControllerName = controllerName;
      MethodName = methodName;
      Parameters = parameters;
      BodySchema = bodySchema;
      AuthRequired = authRequired;
      AuthPolicy = authPolicy;
      ContentHash = contentHash;
      AnalysisConfidence = analysisConfidence;
      AnalysisWarnings = analysisWarnings;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string id, out RdHttpMethod httpMethod, [NotNull] out string route, [NotNull] out string filePath, out int lineNumber, [CanBeNull] out string controllerName, [NotNull] out string methodName, [NotNull] out List<RdApiParameter> parameters, [CanBeNull] out RdApiSchema bodySchema, out bool authRequired, [CanBeNull] out string authPolicy, [NotNull] out string contentHash, out float analysisConfidence, [NotNull] out List<string> analysisWarnings)
    {
      id = Id;
      httpMethod = HttpMethod;
      route = Route;
      filePath = FilePath;
      lineNumber = LineNumber;
      controllerName = ControllerName;
      methodName = MethodName;
      parameters = Parameters;
      bodySchema = BodySchema;
      authRequired = AuthRequired;
      authPolicy = AuthPolicy;
      contentHash = ContentHash;
      analysisConfidence = AnalysisConfidence;
      analysisWarnings = AnalysisWarnings;
    }
    //statics
    
    public static CtxReadDelegate<RdApiEndpoint> Read = (ctx, reader) => 
    {
      var id = reader.ReadString();
      var httpMethod = (RdHttpMethod)reader.ReadInt();
      var route = reader.ReadString();
      var filePath = reader.ReadString();
      var lineNumber = reader.ReadInt();
      var controllerName = ReadStringNullable(ctx, reader);
      var methodName = reader.ReadString();
      var parameters = ReadRdApiParameterList(ctx, reader);
      var bodySchema = ReadRdApiSchemaNullable(ctx, reader);
      var authRequired = reader.ReadBool();
      var authPolicy = ReadStringNullable(ctx, reader);
      var contentHash = reader.ReadString();
      var analysisConfidence = reader.ReadFloat();
      var analysisWarnings = ReadStringList(ctx, reader);
      var _result = new RdApiEndpoint(id, httpMethod, route, filePath, lineNumber, controllerName, methodName, parameters, bodySchema, authRequired, authPolicy, contentHash, analysisConfidence, analysisWarnings);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    public static CtxReadDelegate<List<RdApiParameter>> ReadRdApiParameterList = RdApiParameter.Read.List();
    public static CtxReadDelegate<RdApiSchema> ReadRdApiSchemaNullable = RdApiSchema.Read.NullableClass();
    public static CtxReadDelegate<List<string>> ReadStringList = JetBrains.Rd.Impl.Serializers.ReadString.List();
    
    public static CtxWriteDelegate<RdApiEndpoint> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Id);
      writer.Write((int)value.HttpMethod);
      writer.Write(value.Route);
      writer.Write(value.FilePath);
      writer.Write(value.LineNumber);
      WriteStringNullable(ctx, writer, value.ControllerName);
      writer.Write(value.MethodName);
      WriteRdApiParameterList(ctx, writer, value.Parameters);
      WriteRdApiSchemaNullable(ctx, writer, value.BodySchema);
      writer.Write(value.AuthRequired);
      WriteStringNullable(ctx, writer, value.AuthPolicy);
      writer.Write(value.ContentHash);
      writer.Write(value.AnalysisConfidence);
      WriteStringList(ctx, writer, value.AnalysisWarnings);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    public static  CtxWriteDelegate<List<RdApiParameter>> WriteRdApiParameterList = RdApiParameter.Write.List();
    public static  CtxWriteDelegate<RdApiSchema> WriteRdApiSchemaNullable = RdApiSchema.Write.NullableClass();
    public static  CtxWriteDelegate<List<string>> WriteStringList = JetBrains.Rd.Impl.Serializers.WriteString.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdApiEndpoint) obj);
    }
    public bool Equals(RdApiEndpoint other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Id == other.Id && HttpMethod == other.HttpMethod && Route == other.Route && FilePath == other.FilePath && LineNumber == other.LineNumber && Equals(ControllerName, other.ControllerName) && MethodName == other.MethodName && Parameters.SequenceEqual(other.Parameters) && Equals(BodySchema, other.BodySchema) && AuthRequired == other.AuthRequired && Equals(AuthPolicy, other.AuthPolicy) && ContentHash == other.ContentHash && AnalysisConfidence == other.AnalysisConfidence && AnalysisWarnings.SequenceEqual(other.AnalysisWarnings);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Id.GetHashCode();
        hash = hash * 31 + (int) HttpMethod;
        hash = hash * 31 + Route.GetHashCode();
        hash = hash * 31 + FilePath.GetHashCode();
        hash = hash * 31 + LineNumber.GetHashCode();
        hash = hash * 31 + (ControllerName != null ? ControllerName.GetHashCode() : 0);
        hash = hash * 31 + MethodName.GetHashCode();
        hash = hash * 31 + Parameters.ContentHashCode();
        hash = hash * 31 + (BodySchema != null ? BodySchema.GetHashCode() : 0);
        hash = hash * 31 + AuthRequired.GetHashCode();
        hash = hash * 31 + (AuthPolicy != null ? AuthPolicy.GetHashCode() : 0);
        hash = hash * 31 + ContentHash.GetHashCode();
        hash = hash * 31 + AnalysisConfidence.GetHashCode();
        hash = hash * 31 + AnalysisWarnings.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdApiEndpoint (");
      using (printer.IndentCookie()) {
        printer.Print("id = "); Id.PrintEx(printer); printer.Println();
        printer.Print("httpMethod = "); HttpMethod.PrintEx(printer); printer.Println();
        printer.Print("route = "); Route.PrintEx(printer); printer.Println();
        printer.Print("filePath = "); FilePath.PrintEx(printer); printer.Println();
        printer.Print("lineNumber = "); LineNumber.PrintEx(printer); printer.Println();
        printer.Print("controllerName = "); ControllerName.PrintEx(printer); printer.Println();
        printer.Print("methodName = "); MethodName.PrintEx(printer); printer.Println();
        printer.Print("parameters = "); Parameters.PrintEx(printer); printer.Println();
        printer.Print("bodySchema = "); BodySchema.PrintEx(printer); printer.Println();
        printer.Print("authRequired = "); AuthRequired.PrintEx(printer); printer.Println();
        printer.Print("authPolicy = "); AuthPolicy.PrintEx(printer); printer.Println();
        printer.Print("contentHash = "); ContentHash.PrintEx(printer); printer.Println();
        printer.Print("analysisConfidence = "); AnalysisConfidence.PrintEx(printer); printer.Println();
        printer.Print("analysisWarnings = "); AnalysisWarnings.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: RouteXModel.kt:28</p>
  /// </summary>
  public sealed class RdApiParameter : IPrintable, IEquatable<RdApiParameter>
  {
    //fields
    //public fields
    [NotNull] public string Name {get; private set;}
    [NotNull] public string ParamType {get; private set;}
    public RdParameterSource Source {get; private set;}
    public bool Required {get; private set;}
    [CanBeNull] public string DefaultValue {get; private set;}
    
    //private fields
    //primary constructor
    public RdApiParameter(
      [NotNull] string name,
      [NotNull] string paramType,
      RdParameterSource source,
      bool required,
      [CanBeNull] string defaultValue
    )
    {
      if (name == null) throw new ArgumentNullException("name");
      if (paramType == null) throw new ArgumentNullException("paramType");
      
      Name = name;
      ParamType = paramType;
      Source = source;
      Required = required;
      DefaultValue = defaultValue;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string name, [NotNull] out string paramType, out RdParameterSource source, out bool required, [CanBeNull] out string defaultValue)
    {
      name = Name;
      paramType = ParamType;
      source = Source;
      required = Required;
      defaultValue = DefaultValue;
    }
    //statics
    
    public static CtxReadDelegate<RdApiParameter> Read = (ctx, reader) => 
    {
      var name = reader.ReadString();
      var paramType = reader.ReadString();
      var source = (RdParameterSource)reader.ReadInt();
      var required = reader.ReadBool();
      var defaultValue = ReadStringNullable(ctx, reader);
      var _result = new RdApiParameter(name, paramType, source, required, defaultValue);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    
    public static CtxWriteDelegate<RdApiParameter> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Name);
      writer.Write(value.ParamType);
      writer.Write((int)value.Source);
      writer.Write(value.Required);
      WriteStringNullable(ctx, writer, value.DefaultValue);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdApiParameter) obj);
    }
    public bool Equals(RdApiParameter other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Name == other.Name && ParamType == other.ParamType && Source == other.Source && Required == other.Required && Equals(DefaultValue, other.DefaultValue);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Name.GetHashCode();
        hash = hash * 31 + ParamType.GetHashCode();
        hash = hash * 31 + (int) Source;
        hash = hash * 31 + Required.GetHashCode();
        hash = hash * 31 + (DefaultValue != null ? DefaultValue.GetHashCode() : 0);
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdApiParameter (");
      using (printer.IndentCookie()) {
        printer.Print("name = "); Name.PrintEx(printer); printer.Println();
        printer.Print("paramType = "); ParamType.PrintEx(printer); printer.Println();
        printer.Print("source = "); Source.PrintEx(printer); printer.Println();
        printer.Print("required = "); Required.PrintEx(printer); printer.Println();
        printer.Print("defaultValue = "); DefaultValue.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: RouteXModel.kt:43</p>
  /// </summary>
  public sealed class RdApiSchema : IPrintable, IEquatable<RdApiSchema>
  {
    //fields
    //public fields
    [NotNull] public string TypeName {get; private set;}
    [NotNull] public List<RdApiSchemaProperty> Properties {get; private set;}
    public bool IsArray {get; private set;}
    public bool IsNullable {get; private set;}
    
    //private fields
    //primary constructor
    public RdApiSchema(
      [NotNull] string typeName,
      [NotNull] List<RdApiSchemaProperty> properties,
      bool isArray,
      bool isNullable
    )
    {
      if (typeName == null) throw new ArgumentNullException("typeName");
      if (properties == null) throw new ArgumentNullException("properties");
      
      TypeName = typeName;
      Properties = properties;
      IsArray = isArray;
      IsNullable = isNullable;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string typeName, [NotNull] out List<RdApiSchemaProperty> properties, out bool isArray, out bool isNullable)
    {
      typeName = TypeName;
      properties = Properties;
      isArray = IsArray;
      isNullable = IsNullable;
    }
    //statics
    
    public static CtxReadDelegate<RdApiSchema> Read = (ctx, reader) => 
    {
      var typeName = reader.ReadString();
      var properties = ReadRdApiSchemaPropertyList(ctx, reader);
      var isArray = reader.ReadBool();
      var isNullable = reader.ReadBool();
      var _result = new RdApiSchema(typeName, properties, isArray, isNullable);
      return _result;
    };
    public static CtxReadDelegate<List<RdApiSchemaProperty>> ReadRdApiSchemaPropertyList = RdApiSchemaProperty.Read.List();
    
    public static CtxWriteDelegate<RdApiSchema> Write = (ctx, writer, value) => 
    {
      writer.Write(value.TypeName);
      WriteRdApiSchemaPropertyList(ctx, writer, value.Properties);
      writer.Write(value.IsArray);
      writer.Write(value.IsNullable);
    };
    public static  CtxWriteDelegate<List<RdApiSchemaProperty>> WriteRdApiSchemaPropertyList = RdApiSchemaProperty.Write.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdApiSchema) obj);
    }
    public bool Equals(RdApiSchema other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return TypeName == other.TypeName && Properties.SequenceEqual(other.Properties) && IsArray == other.IsArray && IsNullable == other.IsNullable;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + TypeName.GetHashCode();
        hash = hash * 31 + Properties.ContentHashCode();
        hash = hash * 31 + IsArray.GetHashCode();
        hash = hash * 31 + IsNullable.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdApiSchema (");
      using (printer.IndentCookie()) {
        printer.Print("typeName = "); TypeName.PrintEx(printer); printer.Println();
        printer.Print("properties = "); Properties.PrintEx(printer); printer.Println();
        printer.Print("isArray = "); IsArray.PrintEx(printer); printer.Println();
        printer.Print("isNullable = "); IsNullable.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: RouteXModel.kt:36</p>
  /// </summary>
  public sealed class RdApiSchemaProperty : IPrintable, IEquatable<RdApiSchemaProperty>
  {
    //fields
    //public fields
    [NotNull] public string Name {get; private set;}
    [NotNull] public string PropType {get; private set;}
    public bool Required {get; private set;}
    [NotNull] public List<string> ValidationHints {get; private set;}
    
    //private fields
    //primary constructor
    public RdApiSchemaProperty(
      [NotNull] string name,
      [NotNull] string propType,
      bool required,
      [NotNull] List<string> validationHints
    )
    {
      if (name == null) throw new ArgumentNullException("name");
      if (propType == null) throw new ArgumentNullException("propType");
      if (validationHints == null) throw new ArgumentNullException("validationHints");
      
      Name = name;
      PropType = propType;
      Required = required;
      ValidationHints = validationHints;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string name, [NotNull] out string propType, out bool required, [NotNull] out List<string> validationHints)
    {
      name = Name;
      propType = PropType;
      required = Required;
      validationHints = ValidationHints;
    }
    //statics
    
    public static CtxReadDelegate<RdApiSchemaProperty> Read = (ctx, reader) => 
    {
      var name = reader.ReadString();
      var propType = reader.ReadString();
      var required = reader.ReadBool();
      var validationHints = ReadStringList(ctx, reader);
      var _result = new RdApiSchemaProperty(name, propType, required, validationHints);
      return _result;
    };
    public static CtxReadDelegate<List<string>> ReadStringList = JetBrains.Rd.Impl.Serializers.ReadString.List();
    
    public static CtxWriteDelegate<RdApiSchemaProperty> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Name);
      writer.Write(value.PropType);
      writer.Write(value.Required);
      WriteStringList(ctx, writer, value.ValidationHints);
    };
    public static  CtxWriteDelegate<List<string>> WriteStringList = JetBrains.Rd.Impl.Serializers.WriteString.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdApiSchemaProperty) obj);
    }
    public bool Equals(RdApiSchemaProperty other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Name == other.Name && PropType == other.PropType && Required == other.Required && ValidationHints.SequenceEqual(other.ValidationHints);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Name.GetHashCode();
        hash = hash * 31 + PropType.GetHashCode();
        hash = hash * 31 + Required.GetHashCode();
        hash = hash * 31 + ValidationHints.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdApiSchemaProperty (");
      using (printer.IndentCookie()) {
        printer.Print("name = "); Name.PrintEx(printer); printer.Println();
        printer.Print("propType = "); PropType.PrintEx(printer); printer.Println();
        printer.Print("required = "); Required.PrintEx(printer); printer.Println();
        printer.Print("validationHints = "); ValidationHints.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: RouteXModel.kt:10</p>
  /// </summary>
  public enum RdHttpMethod {
    GET,
    POST,
    PUT,
    DELETE,
    PATCH,
    HEAD,
    OPTIONS
  }
  
  
  /// <summary>
  /// <p>Generated from: RouteXModel.kt:20</p>
  /// </summary>
  public enum RdParameterSource {
    PATH,
    QUERY,
    BODY,
    HEADER,
    FORM
  }
}
